### ISSUE TITLE
Usage instruction

### ISSUE THREAD

**Issue by amimas** [noticeableapp/remarkable-iframify#1]
This seems like a useful plugin. Is this still an active project?

It'd be great if there was a readme with some instructions on how to use this.

**Comment by laurentpellegrino** [comment]
@amimas Thanks for your comment. I have added a [readme](https://github.com/noticeable-app/remarkable-iframify).

This plugin is used in production for our Noticeable changelog as a service. As a consequence, you can expect maintenance. However, adding new features is not planned since in the near future we will switch our editor to a WYSIWYG editor based on [prosemirror](https://prosemirror.net/).

**Comment by amimas** [comment]
Thanks for the quick response
